version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.6.2-stretch-browsers
            - image: circleci/mysql:5.7.21
        steps:
            - checkout
            - run: 
                name: Install Python deps in a venv
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
            - run:
                name: Db Migration
                command: |
                    cp web_app/local_settings_circle_ci.template web_app/local_settings.py
                    python manage.py migrate
            - run:
                name: Run Django server
                background: true
                command: |
                    python manage.py runserver localhost:8000


