version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.6.2-stretch-browsers
            - image: circleci/mysql:5.7.21
        steps:
            - checkout
            - run: 
                name: Install Python deps in a venv
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
            - run:
                name: Install Static deps
                working_directory: ./web_app/static
                command: |
                    sudo apt-get update && sudo apt-get install -y nodejs
                    npm install @angular/cli
                    npm install
                    npm run-script build
            - run:
                name: Db Migration
                working_directory: ./web_app
                command: |
                    . ../venv/bin/activate
                    cp local_settings_circle_ci.template local_settings.py
                    python manage.py migrate
            - run:
                name: Run Django server
                background: true
                working_directory: ./web_app
                command: |
                    . ../venv/bin/activate
                    python manage.py runserver localhost:8000
            - run:
                name: Run Django Test
                working_directory: ./web_app
                command: |
                    . ../venv/bin/activate
                    python manage.py test

