version: 2
jobs:
  build:
    machine:
      python:
        version: 3.6.3
      ruby:
        version: 2.4.0
      node:
        version: 6.6.0
        
    dependencies:
      - pip install --upgrade pip==7.1.2 setuptools==33.1.1 && pip install -r requirements.txt
      - npm install:
        pwd: web_app/static
    steps:
      - checkout
      - run: echo "A first hello"
