version: 2
jobs:
  build:
    machine:
      python:
        version: 3.6.3
      ruby:
        version: 2.4.0
      node:
        version: 6.6.0
    steps:
      - checkout
      - run: echo "A first hello"
