version: 2
jobs:
    build:
        docker:
            - image: lokeshpahal/ubuntu-14.04:latest
            - image: circleci/mysql:5.7.21
        steps:
            - checkout
            - run: 
                name: Install Python deps in a venv
                command: |
                    sudo pip install virtualenv 
                    virtualenv -p python3 env
                    . env/bin/activate
                    pip install -r requirements.txt
            - run:
                name: Install Static deps
                working_directory: ./web_app/static
                command: |
                    echo node --version
                    echo npm --version
                    sudo npm install -g @angular/cli
                    npm install
                    npm run-script build
            - run:
                name: Db Migration
                working_directory: ./web_app
                command: |
                    . ../env/bin/activate
                    cp local_settings_circle_ci.template local_settings.py
                    python manage.py migrate
            - run:
                name: Run Django server
                background: true
                working_directory: ./web_app
                command: |
                    . ../env/bin/activate
                    python manage.py runserver localhost:8000
            - run:
                name: Run Django Test
                working_directory: ./web_app
                command: |
                    . ../env/bin/activate
                    python manage.py test

